FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg sqlite intel-media-driver libva-utils

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY tools/ ./tools/

RUN mkdir -p /media /pictures /app/data /preview-cache /transcode-cache

ENV DATA_DIR=/app/data
ENV MEDIA_ROOTS_DIR=/media
ENV DB_BACKUP_INTERVAL=43200
ENV DB_BACKUP_RETENTION=8
ENV DB_BACKUP_ON_START=0
ENV DB_BACKUP_START_DELAY=120
ENV LOG_RETENTION_DAYS=14
ENV LOG_CLEANUP_INTERVAL=86400
ENV PYTHONDONTWRITEBYTECODE=1
ENV HASH_INTERVAL=30
ENV HASH_BATCH_SIZE=500
ENV HASH_RESOLVE_BATCH_SIZE=1000
ENV HASH_WORKERS=4
ENV BLAKE3_THREADS=2
ENV VIDEO_STREAM_CHUNK_SIZE=1048576
ENV VIDEO_TRANSCODE_CACHE_DIR=/transcode-cache
ENV VIDEO_TRANSCODE_CACHE_MAX_BYTES=900000000
ENV VIDEO_TRANSCODE_ENCODER=libx264
ENV VIDEO_TRANSCODE_GPU_DECODE=auto
ENV VIDEO_TRANSCODE_MAX_EDGE=1280
ENV VIDEO_TRANSCODE_QSV_GLOBAL_QUALITY=28
ENV VIDEO_TRANSCODE_TIMEOUT=1800
ENV VIDEO_TRANSCODE_CONCURRENCY=1
ENV VIDEO_TRANSCODE_CPU_FALLBACK=1
ENV VIDEO_TRANSCODE_VAAPI_FALLBACK=1
ENV VIDEO_TRANSCODE_VAAPI_DEVICE=/dev/dri/renderD128
ENV VIDEO_TRANSCODE_VAAPI_QP=28
ENV VIDEO_TRANSCODE_CPU_MAX_EDGE=960
ENV VIDEO_TRANSCODE_CPU_PRESET=ultrafast
ENV VIDEO_TRANSCODE_CPU_CRF=26
ENV VIDEO_TRANSCODE_CPU_THREADS=2
ENV VIDEO_HLS_SEGMENT_SECONDS=4
ENV IMAGE_PREVIEW_MAX_EDGE=512
ENV IMAGE_PREVIEW_QUALITY=72
ENV IMAGE_PREVIEW_CONCURRENCY=2
ENV IMAGE_PREVIEW_MAX_SOURCE_PIXELS=60000000
ENV IMAGE_PREVIEW_CACHE_DIR=/preview-cache
ENV IMAGE_PREVIEW_CACHE_MAX_BYTES=10000000000
ENV MOVE_DRY_RUN=0
ENV AUTO_MOVE_INODE=1
ENV AUTO_MOVE_HASH_UNIQUE=1
ENV SCAN_INTERVAL=21600
ENV SCAN_ON_START=0

EXPOSE 8848

HEALTHCHECK --interval=30s --timeout=10s --retries=3 --start-period=40s CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8848/api/health', timeout=5).read()"

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8848"]
